# Generated by Django 3.0.5 on 2020-04-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Headline',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('publishTime', models.CharField(max_length=255)),
                ('repost', models.IntegerField()),
                ('comment', models.IntegerField()),
                ('approve', models.IntegerField()),
                ('address', models.URLField()),
            ],
            options={
                'ordering': ['-publishTime'],
            },
        ),
    ]
